apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myproject
  name: web-server
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: myproject
  type: NodePort
